name: test

on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      fail-fast: false
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/UnitTesting/actions/setup@master
        with:
          sublime-text-version: 4
          unittesting-version: master
          display: turbovnc
          # we need xfce for the subl command to work in st3
          window-manager: xfce
      - uses: SublimeText/UnitTesting/actions/run-tests@master
  
